import os

ELEVENLABS_API_KEY = os.getenv("ELEVENLABS_API_KEY", "")
ELEVENLABS_VOICE_ID = os.getenv("ELEVENLABS_VOICE_ID", "")
ELEVENLABS_TTS_MODEL = os.getenv("ELEVENLABS_TTS_MODEL", "eleven_multilingual_v2")
ELEVENLABS_STT_MODEL = os.getenv("ELEVENLABS_STT_MODEL", "scribe_v2")
JARVIS_VOICE_SAMPLE_RATE = int(os.getenv("JARVIS_VOICE_SAMPLE_RATE", "16000"))
JARVIS_VOICE_CHANNELS = int(os.getenv("JARVIS_VOICE_CHANNELS", "1"))
JARVIS_VOICE_RECORD_SECONDS = float(
    os.getenv("JARVIS_VOICE_RECORD_SECONDS", "6")
)
